INSTALL_PATH="/var/www/html/CHANGE_ME";

MYSQL_USER="CHANGE_ME"
MYSQL_PASSWORD="CHANGE_ME"
MYSQL_HOST="localhost"
WORDPRESS_BDD="CHANGE_ME"


WORDPRESS_URL="http://localhost/CHANGE_ME"

WORDPRESS_SITE_NAME="CHANGE_ME"
WORDPRESS_ADMIN_NAME="CHANGE_ME"
WORDPRESS_ADMIN_PASSWORD="CHANGE_ME"
WORDPRESS_ADMIN_EMAIL="CHANGE_ME@mail.com"

# optionnal configurations
WORDPRESS_FOLDER="wordpress"
WORDPRESS_CONTENT_FOLDER="content"
WORDPRESS_TABLE_PREFIX="wp"