MYSQL_USER_DEFAULT="explorateur"
MYSQL_PASSWORD_DEFAULT="Ereul9Aeng"
MYSQL_HOST_DEFAULT="localhost"

WORDPRESS_BDD_DEFAULT="customwordpress"
WORDPRESS_TABLE_PREFIX_DEFAULT="customwp"

WORDPRESS_SITE_NAME_DEFAULT="Custom Wordpress"
WORDPRESS_ADMIN_NAME_DEFAULT="admin"
WORDPRESS_ADMIN_PASSWORD_DEFAULT="admin"
WORDPRESS_ADMIN_EMAIL_DEFAULT="admin@mail.local"

# optionnal configurations
WORDPRESS_FOLDER="wp"
WORDPRESS_CONTENT_FOLDER="content"
